//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRG.LeisureCards.LoadTest
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;
    using GRG.LeisureCards.LoadTest;


    public class PublicSiteTest : WebTest
    {

        private AddSessionTokenPlugIn testPlugin0 = new AddSessionTokenPlugIn();

        public PublicSiteTest()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
            this.PreWebTest += new EventHandler<PreWebTestEventArgs>(this.testPlugin0.PreWebTest);
            this.PostWebTest += new EventHandler<PostWebTestEventArgs>(this.testPlugin0.PostWebTest);
            this.PreTransaction += new EventHandler<PreTransactionEventArgs>(this.testPlugin0.PreTransaction);
            this.PostTransaction += new EventHandler<PostTransactionEventArgs>(this.testPlugin0.PostTransaction);
            this.PrePage += new EventHandler<PrePageEventArgs>(this.testPlugin0.PrePage);
            this.PostPage += new EventHandler<PostPageEventArgs>(this.testPlugin0.PostPage);
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }
            this.PreRequestDataBinding += new EventHandler<PreRequestDataBindingEventArgs>(this.testPlugin0.PreRequestDataBinding);
            this.PreRequest += new EventHandler<PreRequestEventArgs>(this.testPlugin0.PreRequest);
            this.PostRequest += new EventHandler<PostRequestEventArgs>(this.testPlugin0.PostRequest);

            WebTestRequest request1 = new WebTestRequest("http://leisurecardsnpower/");
            WebTestRequest request1Dependent1 = new WebTestRequest("http://leisurecardsnpower/partial/login");
            request1Dependent1.ThinkTime = 4;
            request1Dependent1.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request1Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            request1.DependentRequests.Add(request1Dependent1);
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("http://leisurecardsapi//LeisureCard/Login/12345678/NPower");
            request2.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request2.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            ExtractHttpHeader extractionRule1 = new ExtractHttpHeader();
            extractionRule1.Header = "SessionToken";
            extractionRule1.Required = true;
            extractionRule1.ContextParameterName = "SessionToken";
            request2.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule1.Extract);
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("http://leisurecardsnpower/partial/offers");
            request3.ThinkTime = 2;
            request3.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request3.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("http://leisurecardsnpower/partial/offers_241");
            request4.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request4.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("http://leisurecardsapi//TwoForOne/GetAll");
            request5.Method = "OPTIONS";
            StringHttpBody request5Body = new StringHttpBody();
            request5Body.ContentType = "";
            request5Body.InsertByteOrderMark = false;
            request5Body.BodyString = "";
            request5.Body = request5Body;
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest("http://leisurecardsapi//TwoForOne/GetAll");
            request6.ThinkTime = 8;
            request6.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request6.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest("http://leisurecardsapi//TwoForOne/FindByLocation/Aylesbury/5000");
            request7.Method = "OPTIONS";
            StringHttpBody request7Body = new StringHttpBody();
            request7Body.ContentType = "";
            request7Body.InsertByteOrderMark = false;
            request7Body.BodyString = "";
            request7.Body = request7Body;
            yield return request7;
            request7 = null;

            WebTestRequest request8 = new WebTestRequest("http://leisurecardsapi//TwoForOne/FindByLocation/Aylesbury/5000");
            request8.Method = "OPTIONS";
            StringHttpBody request8Body = new StringHttpBody();
            request8Body.ContentType = "";
            request8Body.InsertByteOrderMark = false;
            request8Body.BodyString = "";
            request8.Body = request8Body;
            yield return request8;
            request8 = null;

            WebTestRequest request9 = new WebTestRequest("http://leisurecardsapi//TwoForOne/FindByLocation/Aylesbury/5000");
            request9.Method = "OPTIONS";
            StringHttpBody request9Body = new StringHttpBody();
            request9Body.ContentType = "";
            request9Body.InsertByteOrderMark = false;
            request9Body.BodyString = "";
            request9.Body = request9Body;
            yield return request9;
            request9 = null;

            WebTestRequest request10 = new WebTestRequest("http://leisurecardsapi//TwoForOne/FindByLocation/Aylesbury/5000");
            request10.Method = "OPTIONS";
            StringHttpBody request10Body = new StringHttpBody();
            request10Body.ContentType = "";
            request10Body.InsertByteOrderMark = false;
            request10Body.BodyString = "";
            request10.Body = request10Body;
            yield return request10;
            request10 = null;

            WebTestRequest request11 = new WebTestRequest("http://leisurecardsapi//TwoForOne/FindByLocation/Aylesbury/5000");
            request11.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request11.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            yield return request11;
            request11 = null;

            WebTestRequest request12 = new WebTestRequest("http://leisurecardsapi//TwoForOne/FindByLocation/Aylesbury/5000");
            request12.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request12.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            yield return request12;
            request12 = null;

            WebTestRequest request13 = new WebTestRequest("http://leisurecardsapi//TwoForOne/FindByLocation/Aylesbury/5000");
            request13.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request13.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            yield return request13;
            request13 = null;

            WebTestRequest request14 = new WebTestRequest("http://leisurecardsapi//TwoForOne/FindByLocation/Aylesbury/5000");
            request14.ThinkTime = 3;
            request14.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request14.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            yield return request14;
            request14 = null;

            WebTestRequest request15 = new WebTestRequest("http://leisurecardsnpower/partial/offers_241_details");
            request15.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request15.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            yield return request15;
            request15 = null;

            WebTestRequest request16 = new WebTestRequest("http://maps.googleapis.com/maps/api/js");
            request16.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            request16.QueryStringParameters.Add("sensor", "false", false, false);
            request16.QueryStringParameters.Add("language", "en", false, false);
            request16.QueryStringParameters.Add("callback", "initMap", false, false);
            yield return request16;
            request16 = null;

            WebTestRequest request17 = new WebTestRequest("http://leisurecardsapi//TwoForOne/Get/5");
            request17.Method = "OPTIONS";
            StringHttpBody request17Body = new StringHttpBody();
            request17Body.ContentType = "";
            request17Body.InsertByteOrderMark = false;
            request17Body.BodyString = "";
            request17.Body = request17Body;
            yield return request17;
            request17 = null;

            WebTestRequest request18 = new WebTestRequest("http://leisurecardsapi//TwoForOne/Get/5");
            request18.Method = "OPTIONS";
            StringHttpBody request18Body = new StringHttpBody();
            request18Body.ContentType = "";
            request18Body.InsertByteOrderMark = false;
            request18Body.BodyString = "";
            request18.Body = request18Body;
            yield return request18;
            request18 = null;

            WebTestRequest request19 = new WebTestRequest("http://leisurecardsnpower/Content/NPower/241Category/");
            request19.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            yield return request19;
            request19 = null;

            WebTestRequest request20 = new WebTestRequest("http://leisurecardsapi//TwoForOne/Get/5");
            request20.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request20.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            yield return request20;
            request20 = null;

            WebTestRequest request21 = new WebTestRequest("http://leisurecardsapi//TwoForOne/Get/5");
            request21.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request21.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            yield return request21;
            request21 = null;

            WebTestRequest request22 = new WebTestRequest("http://maps.googleapis.com/maps/gen_204");
            request22.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            request22.QueryStringParameters.Add("target", "api", false, false);
            request22.QueryStringParameters.Add("ev", "api_viewport", false, false);
            request22.QueryStringParameters.Add("cad", "host:leisurecardsnpower,v:21,r:1,mt:m,c:-34.396976%2C150.644,sp:0.12635x0.18642,s" +
                    "ize:543x446,relsize:0.16,token:40pqbd6vkv,src:apiv3,ts:9bjevq", false, false);
            yield return request22;
            request22 = null;

            WebTestRequest request23 = new WebTestRequest("http://fonts.gstatic.com/s/roboto/v15/Hgo13k-tfSpn0qi1SFdUfT8E0i7KZn-EPnyo3HZu7kw" +
                    ".woff");
            request23.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            yield return request23;
            request23 = null;

            WebTestRequest request24 = new WebTestRequest("http://fonts.gstatic.com/s/roboto/v15/2UX7WLTfW3W8TclTUvlFyQ.woff");
            request24.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            yield return request24;
            request24 = null;

            WebTestRequest request25 = new WebTestRequest("http://fonts.gstatic.com/s/roboto/v15/RxZJdnzeo3R5zSexge8UUT8E0i7KZn-EPnyo3HZu7kw" +
                    ".woff");
            request25.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            yield return request25;
            request25 = null;

            WebTestRequest request26 = new WebTestRequest("http://fonts.gstatic.com/s/roboto/v15/d-6IYplOFocCacKzxwXSOD8E0i7KZn-EPnyo3HZu7kw" +
                    ".woff");
            request26.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            yield return request26;
            request26 = null;

            WebTestRequest request27 = new WebTestRequest("http://maps.googleapis.com/maps/api/js/ViewportInfoService.GetViewportInfo");
            request27.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            request27.QueryStringParameters.Add("", "1m6", false, false);
            request27.QueryStringParameters.Add("", "1m2", false, false);
            request27.QueryStringParameters.Add("", "1d-34.59394610130113", false, false);
            request27.QueryStringParameters.Add("", "2d150.3535276133979", false, false);
            request27.QueryStringParameters.Add("", "2m2", false, false);
            request27.QueryStringParameters.Add("", "1d-34.20226884449311", false, false);
            request27.QueryStringParameters.Add("", "2d150.93472612350013", false, false);
            request27.QueryStringParameters.Add("", "2u12", false, false);
            request27.QueryStringParameters.Add("", "4sen", false, false);
            request27.QueryStringParameters.Add("", "5e0", false, false);
            request27.QueryStringParameters.Add("", "6sm%40313000000", false, false);
            request27.QueryStringParameters.Add("", "7b0", false, false);
            request27.QueryStringParameters.Add("", "8e0", false, false);
            request27.QueryStringParameters.Add("", "9b0", false, false);
            request27.QueryStringParameters.Add("callback", "_xdc_._jb3xmg", false, false);
            request27.QueryStringParameters.Add("token", "111265", false, false);
            yield return request27;
            request27 = null;

            WebTestRequest request28 = new WebTestRequest("http://mt0.googleapis.com/vt");
            request28.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            request28.QueryStringParameters.Add("pb", @"!1m4!1m3!1i12!2i3760!3i2464!1m4!1m3!1i12!2i3760!3i2465!1m4!1m3!1i12!2i3761!3i2464!1m4!1m3!1i12!2i3761!3i2465!1m4!1m3!1i12!2i3760!3i2466!1m4!1m3!1i12!2i3761!3i2466!1m4!1m3!1i12!2i3762!3i2464!1m4!1m3!1i12!2i3762!3i2465!1m4!1m3!1i12!2i3763!3i2464!1m4!1m3!1i12!2i3763!3i2465!1m4!1m3!1i12!2i3762!3i2466!1m4!1m3!1i12!2i3763!3i2466!2m3!1e0!2sm!3i313208537!3m9!2sen!3sUS!5e18!12m1!1e47!12m3!1e37!2m1!1ssmartmaps!4e3", false, false);
            request28.QueryStringParameters.Add("callback", "_xdc_._wgxwtw", false, false);
            request28.QueryStringParameters.Add("token", "129609", false, false);
            yield return request28;
            request28 = null;

            WebTestRequest request29 = new WebTestRequest("http://csi.gstatic.com/csi");
            request29.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            request29.QueryStringParameters.Add("v", "2", false, false);
            request29.QueryStringParameters.Add("s", "mapsapi3", false, false);
            request29.QueryStringParameters.Add("action", "apiboot", false, false);
            request29.QueryStringParameters.Add("rt", "jl.33,mc.50,mb.155,smv.331,dm.331,prt.331,plt.314,ep.579,vt.852,mt.852", false, false);
            request29.QueryStringParameters.Add("size", "547x450", false, false);
            request29.QueryStringParameters.Add("maptype", "m", false, false);
            yield return request29;
            request29 = null;

            WebTestRequest request30 = new WebTestRequest("http://maps.googleapis.com/maps/api/js/AuthenticationService.Authenticate");
            request30.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            request30.QueryStringParameters.Add("", "1shttp%3A%2F%2Fleisurecardsnpower%2F%23%2Foffers%2F241%2F5", false, false);
            request30.QueryStringParameters.Add("", "5e1", false, false);
            request30.QueryStringParameters.Add("callback", "_xdc_._5mmuf1", false, false);
            request30.QueryStringParameters.Add("token", "873", false, false);
            yield return request30;
            request30 = null;

            WebTestRequest request31 = new WebTestRequest("http://maps.googleapis.com/maps/api/js/GeocodeService.Search");
            request31.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            request31.QueryStringParameters.Add("", "4sCT7%200BH", false, false);
            request31.QueryStringParameters.Add("", "7sUS", false, false);
            request31.QueryStringParameters.Add("", "9sen", false, false);
            request31.QueryStringParameters.Add("callback", "_xdc_._qghvv3", false, false);
            request31.QueryStringParameters.Add("token", "40637", false, false);
            yield return request31;
            request31 = null;

            WebTestRequest request32 = new WebTestRequest("http://csi.gstatic.com/csi");
            request32.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            request32.QueryStringParameters.Add("v", "2", false, false);
            request32.QueryStringParameters.Add("s", "mapsapi3", false, false);
            request32.QueryStringParameters.Add("action", "apiboot2", false, false);
            request32.QueryStringParameters.Add("rt", "main.35,firstmap.50", false, false);
            yield return request32;
            request32 = null;

            WebTestRequest request33 = new WebTestRequest("http://maps.googleapis.com/maps/gen_204");
            request33.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            request33.QueryStringParameters.Add("target", "api", false, false);
            request33.QueryStringParameters.Add("ev", "api_viewport", false, false);
            request33.QueryStringParameters.Add("cad", "host:leisurecardsnpower,v:21,r:1,mt:m,c:51.36672%2C1.316269,sp:0.09560x0.18642,si" +
                    "ze:543x446,relsize:0.16,token:40pqbd6vkv,src:apiv3,ts:9bjflz", false, false);
            yield return request33;
            request33 = null;

            WebTestRequest request34 = new WebTestRequest("http://maps.googleapis.com/maps/gen_204");
            request34.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            request34.QueryStringParameters.Add("target", "api", false, false);
            request34.QueryStringParameters.Add("ev", "api_maprft", false, false);
            request34.QueryStringParameters.Add("cad", "host:leisurecardsnpower,v:21,r:1,t:498,smni:1,src:apiv3,token:40pqbd6vkv,ts:9bjfm" +
                    "1", false, false);
            yield return request34;
            request34 = null;

            WebTestRequest request35 = new WebTestRequest("http://mt0.googleapis.com/vt");
            request35.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            request35.QueryStringParameters.Add("pb", @"!1m4!1m3!1i12!2i2061!3i1363!1m4!1m3!1i12!2i2062!3i1363!1m4!1m3!1i12!2i2063!3i1363!1m4!1m3!1i12!2i2061!3i1364!1m4!1m3!1i12!2i2061!3i1365!1m4!1m3!1i12!2i2062!3i1364!1m4!1m3!1i12!2i2062!3i1365!1m4!1m3!1i12!2i2063!3i1364!1m4!1m3!1i12!2i2063!3i1365!1m4!1m3!1i12!2i2064!3i1363!1m4!1m3!1i12!2i2064!3i1364!1m4!1m3!1i12!2i2064!3i1365!2m3!1e0!2sm!3i313208537!3m9!2sen!3sUS!5e18!12m1!1e47!12m3!1e37!2m1!1ssmartmaps!4e3", false, false);
            request35.QueryStringParameters.Add("callback", "_xdc_._43ndww", false, false);
            request35.QueryStringParameters.Add("token", "23613", false, false);
            yield return request35;
            request35 = null;

            WebTestRequest request36 = new WebTestRequest("http://maps.googleapis.com/maps/api/js/ViewportInfoService.GetViewportInfo");
            request36.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            request36.QueryStringParameters.Add("", "1m6", false, false);
            request36.QueryStringParameters.Add("", "1m2", false, false);
            request36.QueryStringParameters.Add("", "1d51.22200137235361", false, false);
            request36.QueryStringParameters.Add("", "2d1.0324703524102005", false, false);
            request36.QueryStringParameters.Add("", "2m2", false, false);
            request36.QueryStringParameters.Add("", "1d51.51835860313804", false, false);
            request36.QueryStringParameters.Add("", "2d1.5965050819677344", false, false);
            request36.QueryStringParameters.Add("", "2u12", false, false);
            request36.QueryStringParameters.Add("", "4sen", false, false);
            request36.QueryStringParameters.Add("", "5e0", false, false);
            request36.QueryStringParameters.Add("", "6sm%40313000000", false, false);
            request36.QueryStringParameters.Add("", "7b0", false, false);
            request36.QueryStringParameters.Add("", "8e0", false, false);
            request36.QueryStringParameters.Add("", "9b0", false, false);
            request36.QueryStringParameters.Add("callback", "_xdc_._ksxlpp", false, false);
            request36.QueryStringParameters.Add("token", "111176", false, false);
            yield return request36;
            request36 = null;

            WebTestRequest request37 = new WebTestRequest("http://csi.gstatic.com/csi");
            request37.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            request37.QueryStringParameters.Add("v", "2", false, false);
            request37.QueryStringParameters.Add("s", "mapsapi3", false, false);
            request37.QueryStringParameters.Add("action", "map", false, false);
            request37.QueryStringParameters.Add("rt", "visuallycomplete.281", false, false);
            request37.QueryStringParameters.Add("e", "staticmap", false, false);
            yield return request37;
            request37 = null;

            WebTestRequest request38 = new WebTestRequest("http://mt0.googleapis.com/vt");
            request38.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            request38.QueryStringParameters.Add("pb", @"!1m4!1m3!1i12!2i2061!3i1363!1m4!1m3!1i12!2i2062!3i1363!1m4!1m3!1i12!2i2063!3i1363!1m4!1m3!1i12!2i2061!3i1364!1m4!1m3!1i12!2i2061!3i1365!1m4!1m3!1i12!2i2062!3i1364!1m4!1m3!1i12!2i2062!3i1365!1m4!1m3!1i12!2i2063!3i1364!1m4!1m3!1i12!2i2063!3i1365!1m4!1m3!1i12!2i2064!3i1363!1m4!1m3!1i12!2i2064!3i1364!1m4!1m3!1i12!2i2064!3i1365!2m3!1e0!2sm!3i313209258!3m9!2sen!3sUS!5e18!12m1!1e47!12m3!1e37!2m1!1ssmartmaps!4e3", false, false);
            request38.QueryStringParameters.Add("callback", "_xdc_._qh81mq", false, false);
            request38.QueryStringParameters.Add("token", "47099", false, false);
            yield return request38;
            request38 = null;

            WebTestRequest request39 = new WebTestRequest("http://maps.googleapis.com/maps/gen_204");
            request39.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            request39.QueryStringParameters.Add("target", "api", false, false);
            request39.QueryStringParameters.Add("ev", "api_maprft", false, false);
            request39.QueryStringParameters.Add("cad", "host:leisurecardsnpower,v:21,r:1,t:1164,smni:1,src:apiv3,token:40pqbd6vkv,ts:9bjg" +
                    "4j", false, false);
            yield return request39;
            request39 = null;

            WebTestRequest request40 = new WebTestRequest("http://leisurecardsapi//TwoForOne/ClaimOffer/5");
            request40.Method = "OPTIONS";
            StringHttpBody request40Body = new StringHttpBody();
            request40Body.ContentType = "";
            request40Body.InsertByteOrderMark = false;
            request40Body.BodyString = "";
            request40.Body = request40Body;
            yield return request40;
            request40 = null;

            WebTestRequest request41 = new WebTestRequest("http://leisurecardsapi//TwoForOne/ClaimOffer/5");
            request41.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request41.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            yield return request41;
            request41 = null;

            WebTestRequest request42 = new WebTestRequest("http://leisurecardsnpower/pdf/241voucher/5/5b53c5fb-9adb-477e-a741-24aefb8ecd00");
            yield return request42;
            request42 = null;

            WebTestRequest request43 = new WebTestRequest("http://leisurecardsnpower/pdf/241voucher/5/5b53c5fb-9adb-477e-a741-24aefb8ecd00");
            yield return request43;
            request43 = null;

            WebTestRequest request44 = new WebTestRequest("http://csi.gstatic.com/csi");
            request44.ThinkTime = 3;
            request44.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            request44.QueryStringParameters.Add("v", "2", false, false);
            request44.QueryStringParameters.Add("s", "mapsapi3", false, false);
            request44.QueryStringParameters.Add("action", "geocoder", false, false);
            request44.QueryStringParameters.Add("rt", "gsc.104", false, false);
            yield return request44;
            request44 = null;

            WebTestRequest request45 = new WebTestRequest("http://maps.googleapis.com/maps/api/js/QuotaService.RecordEvent");
            request45.ThinkTime = 24;
            request45.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            request45.QueryStringParameters.Add("", "1shttp%3A%2F%2Fleisurecardsnpower%2F%23%2Foffers%2F241%2F5", false, false);
            request45.QueryStringParameters.Add("", "4e1", false, false);
            request45.QueryStringParameters.Add("", "5e0", false, false);
            request45.QueryStringParameters.Add("", "6u1", false, false);
            request45.QueryStringParameters.Add("", "7s9bjj5f", false, false);
            request45.QueryStringParameters.Add("callback", "_xdc_._f62gz9", false, false);
            request45.QueryStringParameters.Add("token", "112715", false, false);
            yield return request45;
            request45 = null;

            WebTestRequest request46 = new WebTestRequest("http://leisurecardsnpower/");
            request46.ExpectedResponseUrl = "http://leisurecardsnpower/#/offers/241?location=Aylesbury&miles=5000#241search";
            request46.QueryStringParameters.Add("location", "Aylesbury", false, false);
            request46.QueryStringParameters.Add("miles", "5000", false, false);
            yield return request46;
            request46 = null;

            WebTestRequest request47 = new WebTestRequest("http://leisurecardsapi//TwoForOne/FindByLocation/Aylesbury/5000");
            request47.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request47.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/#/offers/241?location=Aylesbury&miles=5000#241search"));
            yield return request47;
            request47 = null;

            WebTestRequest request48 = new WebTestRequest("http://leisurecardsapi//TwoForOne/FindByLocation/Aylesbury/5000");
            request48.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request48.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/#/offers/241?location=Aylesbury&miles=5000#241search"));
            yield return request48;
            request48 = null;

            WebTestRequest request49 = new WebTestRequest("http://leisurecardsnpower/");
            WebTestRequest request49Dependent1 = new WebTestRequest("http://leisurecardsnpower/partial/login");
            request49Dependent1.ThinkTime = 4;
            request49Dependent1.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request49Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            request49.DependentRequests.Add(request49Dependent1);
            yield return request49;
            request49 = null;

            WebTestRequest request50 = new WebTestRequest("http://leisurecardsapi//LeisureCard/Login/12345678/NPower");
            request50.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request50.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            yield return request50;
            request50 = null;

            WebTestRequest request51 = new WebTestRequest("http://leisurecardsnpower/partial/offers");
            request51.ThinkTime = 1;
            request51.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request51.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            yield return request51;
            request51 = null;

            WebTestRequest request52 = new WebTestRequest("http://leisurecardsnpower/partial/offers_discount");
            request52.ThinkTime = 1;
            request52.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request52.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            yield return request52;
            request52 = null;

            WebTestRequest request53 = new WebTestRequest("http://leisurecardsnpower/partial/offers_discount_cottage");
            request53.ThinkTime = 2;
            request53.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request53.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/"));
            yield return request53;
            request53 = null;

            WebTestRequest request54 = new WebTestRequest("http://leisurecardsnpower/");
            request54.ThinkTime = 1;
            request54.ExpectedResponseUrl = "http://leisurecardsnpower/#/offers/discount";
            yield return request54;
            request54 = null;

            WebTestRequest request55 = new WebTestRequest("http://leisurecardsnpower/partial/offers_discount_hoseasons");
            request55.ThinkTime = 5;
            request55.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request55.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/#/offers/discount"));
            yield return request55;
            request55 = null;

            WebTestRequest request56 = new WebTestRequest("http://leisurecardsnpower/partial/offers_experience");
            request56.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request56.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/#/offers/discount"));
            yield return request56;
            request56 = null;

            WebTestRequest request57 = new WebTestRequest("http://leisurecardsapi//RedLetter/GetRandomSpecialOffers/6");
            request57.Method = "OPTIONS";
            StringHttpBody request57Body = new StringHttpBody();
            request57Body.ContentType = "";
            request57Body.InsertByteOrderMark = false;
            request57Body.BodyString = "";
            request57.Body = request57Body;
            yield return request57;
            request57 = null;

            WebTestRequest request58 = new WebTestRequest("http://leisurecardsapi//RedLetter/GetRandomSpecialOffers/6");
            request58.Method = "OPTIONS";
            StringHttpBody request58Body = new StringHttpBody();
            request58Body.ContentType = "";
            request58Body.InsertByteOrderMark = false;
            request58Body.BodyString = "";
            request58.Body = request58Body;
            yield return request58;
            request58 = null;

            WebTestRequest request59 = new WebTestRequest("http://leisurecardsapi//RedLetter/GetRandomSpecialOffers/6");
            request59.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request59.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/#/offers/discount"));
            yield return request59;
            request59 = null;

            WebTestRequest request60 = new WebTestRequest("http://leisurecardsapi//RedLetter/GetRandomSpecialOffers/6");
            request60.ThinkTime = 4;
            request60.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request60.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/#/offers/discount"));
            yield return request60;
            request60 = null;

            WebTestRequest request61 = new WebTestRequest("http://leisurecardsapi//RedLetter/GetRandomSpecialOffers/6");
            request61.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request61.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/#/offers/discount"));
            yield return request61;
            request61 = null;

            WebTestRequest request62 = new WebTestRequest("http://leisurecardsapi//RedLetter/GetRandomSpecialOffers/6");
            request62.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request62.Headers.Add(new WebTestRequestHeader("Referer", "http://leisurecardsnpower/#/offers/discount"));
            yield return request62;
            request62 = null;
        }
    }
}
